[package]
name = "db-dump"
version = "0.3.5" # remember to update html_root_url
authors = ["David Tolnay <dtolnay@gmail.com>"]
description = "Library for scripting analyses against crates.io's database dumps"
documentation = "https://docs.rs/db-dump"
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/dtolnay/db-dump"

[dependencies]
chrono = "0.4"
csv = "1.1"
flate2 = "1.0"
fnv = "1.0"
indicatif = "0.17"
memmap = "0.7"
once_cell = "1.0"
semver = { version = "1.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tar = "0.4"

[workspace]
members = ["concat"]
